// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyoslhlmngkdxgscvkos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95b3NsaGxtbmdrZHhnc2N2a29zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5Nzk5MDYsImV4cCI6MjA1ODU1NTkwNn0.Iv-rZu9FfDQMdNn7yGEZgUTsxXafdYeaFSRj44WSzk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);